spring:
  profiles:
    active: por
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.88.110:3306/dbgirl?characterEncoding=utf8
     username: root
     password: 123
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true

